In [ ]:
import numpy as np

'2.4.1'

In [ ]:
my_list = [1, 2,3,4]
arr = np.array(my_list)
print(arr)

numpy.ndarray

In [8]:
arr.shape

(4,)

In [ ]:
my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [3,4,5,6,7]
nested_arr= np.array([my_list1,my_list2,my_list3])
nested_arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [14]:
nested_arr.shape

(3, 5)

In [20]:
nested_arr.reshape(5,3)  # this will only work if number of element in reshaping is same , reshaping in (2,2) give error bcause it will have 4 element

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [26]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [28]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [30]:
np.random.rand(3,3)

array([[0.43880325, 0.35817182, 0.33341037],
       [0.79715752, 0.52074298, 0.89837222],
       [0.36515341, 0.71933004, 0.6044785 ]])